name: CI Pipeline

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main, development]

jobs:
    test:
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm ci

            - name: Run security audit
              run: npm audit --audit-level=moderate

            - name: Type check
              run: npm run type-check

            - name: Run esLint
              run: npm run lint:eslint

            - name: Run prettier
              run: npm run format:check

            - name: Run test coverage
              run: npm run test:coverage
